
[buildpack]
id = "com.starkandwayne.cf-pancake"
name = "CF Pancake Buildpack"
version = "0.3.0"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
